<?xml version="1.0"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <service name="AVM_ServerStatus">
    <port binding="AVM_ServerStatus" name="ScanInfo">
      <soap:address location="http://fritz.box:49000/MediaServer/ServerStatus/Control"/>
    </port>
  </service>
  <binding name="AVM_ServerStatus" type="AVM_ServerStatus">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="ScanInfo">
      <soap:operation soapAction="urn:avm.de:service:AVM_ServerStatus:1#ScanInfo"/>
      <input>
        <soap:body use="encoded" namespace="urn:avm.de:service:AVM_ServerStatus:1" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </input>
      <output>
        <soap:body use="encoded" namespace="urn:avm.de:service:AVM_ServerStatus:1" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>
  </binding>
  <portType name="AVM_ServerStatus">
    <operation name="ScanInfo">
      <input message="ScanInfoRequest"/>
      <output message="ScanInfoResponse"/>
    </operation>
  </portType>
  <message name="ScanInfoRequest"/>
  <message name="ScanInfoResponse">
    <part type="xsd:string" name="StartTime"/>
    <part type="xsd:string" name="EndTime"/>
    <part type="xsd:unsignedInt" name="AudioFiles"/>
    <part type="xsd:unsignedInt" name="MovieFiles"/>
    <part type="xsd:unsignedInt" name="ImageFiles"/>
  </message>
</definitions>
