<?xml version="1.0"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <service name="WANEthernetLinkConfig1">
    <documentation>http://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/wanethlinkconfigSCPD.pdf</documentation>
    <port binding="WANEthernetLinkConfig1" name="GetEthernetLinkStatus">
      <soap:address location="http://fritz.box:49000/upnp/control/wanethlinkconfig1"/>
    </port>
  </service>
  <binding name="WANEthernetLinkConfig1" type="WANEthernetLinkConfig1">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="GetEthernetLinkStatus">
      <soap:operation soapAction="urn:dslforum-org:service:WANEthernetLinkConfig:1#GetEthernetLinkStatus"/>
      <input>
        <soap:body use="encoded" namespace="urn:dslforum-org:service:WANEthernetLinkConfig:1" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </input>
      <output>
        <soap:body use="encoded" namespace="urn:dslforum-org:service:WANEthernetLinkConfig:1" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
      </output>
    </operation>
  </binding>
  <portType name="WANEthernetLinkConfig1">
    <operation name="GetEthernetLinkStatus">
      <input message="GetEthernetLinkStatusRequest"/>
      <output message="GetEthernetLinkStatusResponse"/>
    </operation>
  </portType>
  <message name="GetEthernetLinkStatusRequest"/>
  <message name="GetEthernetLinkStatusResponse">
    <part type="xsd:string" name="NewEthernetLinkStatus"/>
  </message>
</definitions>
